sudo: required
dist: trusty

services:
  - docker

language: python
matrix:
    include:
        - python: 3.5
          dist: trusty
          sudo: false
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true
        - python: pypy
          dist: trusty
          sudo: false

install:
  - if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then pip install enum34; fi
  - pip install pipenv

script:
  - make test
