language: python

services:
  - docker

matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          python: 3.6
        - os: osx
          language: generic

install:
  - ./.travis/install.sh

script:
  - make test
